name: MERGE_MAIN_TO_DEVELOP
on:
  push:
    branches:
    - "main"

jobs:
  Merge_main_to_develop:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout develop
      uses: actions/checkout@v4
      with:
        ref: develop
        fetch-depth: 0
    - name: Merge main to develop and push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git merge -m 'Merge main to develop' --no-edit origin/main
        git push
    - name: Notify on Slack if merge fails
      uses: slackapi/slack-github-action@v1.15.0
      if: failure()
      with:
        channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
        slack-message: "Automatic merge of <https://github.com/${{ github.repository }}/tree/${{ github.ref }}|${{ github.ref }}> to <https://github.com/${{ github.repository }}/tree/develop|${{ github.repository }}#develop> failed."
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
